version: '3.8'

services:
  # Apache + PHP Service
  web:
    image: php:8.2-apache
    container_name: lamp_web
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DB=mydatabase
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql &&
             a2enmod rewrite &&
             apache2-foreground"
    networks:
      - lamp-network
    restart: always

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: lamp_mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    networks:
      - lamp-network
    restart: always

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - lamp-network
    restart: always

networks:
  lamp-network:
    driver: bridge

volumes:
  mysql_data: